import Link from 'next/link'

export const metadata = {
    title: "Tienda",
    description: "Generated by create next app",
}

export default function TiendaLayout({ children }) {
    return (
        <>
            <nav className="bg-emerald-400 text-gray-400 p-3">
                <ul>
                    <li>
                        <Link href="/tienda/alimentacion">Alimentación</Link>
                    </li>
                    <li>
                        <Link href="/tienda/deportes">Deportes</Link>
                    </li>
                    <li>
                        <Link href="/tienda">Tienda</Link>
                    </li>
                </ul>
            </nav>
            {children}
        </>
    )
}